#!/bin/bash
# Runs the memory transitions app

#../../../pin -t obj-intel64/memtrans_multi.so -o memtrans_multi.out -s 12582912 -ic 1 -a 16 -- ls

#../../../pin -t obj-intel64/memtrans_multi.so -o memtrans_multi.out -s 65536 -a 4 -- ls

../../../pin -t obj-intel64/memtrans_multi.so -o memtrans_multi.out -s 4194304 -a $1 -- ls

#../../../pin -t obj-intel64/memtrans_multi_samp.so -o memtrans_multi_samp.out -s $1 -a $2 -- ls
